using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SportBar_0.MVVM.View
{

    /// <summary>
    /// This class represents the total sum of hours and gross revenue for the sports bar.
    /// It's likely used in the View layer of an MVVM architecture for data binding.
    /// </summary>  
    public class TotalSum
    {
        /// <summary>
        /// Gets or sets the total number of hours spent by customers at the sports bar.
        /// </summary>
        public int SHours { get; set; }

        /// <summary>
        /// Gets or sets the total gross revenue generated by the sports bar.
        /// </summary>
        public int SGro { get; set; }
    }
}
